export const EXTERNAL_AMENITIES = [
    { name: 'Swimming Pool', icon: '🏊' },
    { name: 'Club House', icon: '🏛️' },
    { name: 'Kids Play Area', icon: '🛝' },
    { name: 'Garden', icon: '🌳' },
    { name: 'Multi Purpose Court', icon: '🏀' },
    { name: 'Golf Course', icon: '⛳' },
    { name: 'Senior Citizen Area', icon: '👴' },
    { name: 'Squash Court', icon: '🎾' },
    { name: 'Pets Walking Area', icon: '🐾' },
    { name: 'Multi Purpose Lawn', icon: '🌱' },
    { name: 'Box Cricket', icon: '🏏' },
    { name: 'Library', icon: '📚' },
    { name: 'Open Gym', icon: '🏋️' },
    { name: 'Amphitheater', icon: '🎭' },
    { name: 'Banquet Hall', icon: '🎊' },
    { name: 'Toddlers Play Area', icon: '🧸' },
    { name: 'Seating Area', icon: '🪑' },
    { name: 'Creche Outdoor Play Area', icon: '🎈' },
    { name: 'Table Tennis', icon: '🏓' },
    { name: 'Pet Park', icon: '🐶' },
    { name: 'Indoor games', icon: '🎲' },
    { name: 'Star Gazing', icon: '✨' },
    { name: 'Badminton Court', icon: '🏸' },
    { name: 'Skating Ring', icon: '⛸️' },
    { name: 'Gymnasium', icon: '💪' },
    { name: 'Mini Theatre', icon: '🎬' },
    { name: 'Multi purpose hall', icon: '🏢' },
];
